### ISSUE TITLE
will_paginate

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/kilter#11]
@MarinaMartin just mentioned this to me. Does it do what Kilter does?

- https://github.com/mislav/will_paginate
- https://rubygems.org/gems/will_paginate/versions/3.1.0

**Comment by mphprogrammer** [comment]
Like will_paginate, it paginates. Although will_paginate ties directly into active_record, and therefore can provide filtering, kilter also provides filtering but counts the results for each column. So there are some differences.
