### ISSUE TITLE
README Out of date

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/kilter#2]
Has some template stuff in there

**Comment by plusjeff** [comment]
Things to add:

- [ ] Remove template text (like @paultag said)
- [ ] Add an example of how to use (or point to a unit test, etc.)
- [ ] How someone can contribute to the project
- [ ] What do increments in major/minor/minor-minor [versions mean](https://github.com/department-of-veterans-affairs/kilter/blob/master/lib/kilter/version.rb#L2)
