### ISSUE TITLE
Make DEFAULT_PAGE_SIZE easier to understand

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/kilter#5]
https://github.com/department-of-veterans-affairs/kilter/blob/master/lib/kilter.rb#L7

Warning: This is super nitpicky :smirk_cat: 

A few things:

- `DEFAULT_PAGE_SIZE` has an unclear name on what it is. Maybe `DEFAULT_ITEMS_PER_PAGE`?
- 9 is an odd number for a default. Maybe 5 or 10? (like I said, super nitpicky...sorry)

**Comment by mphprogrammer** [comment]
I will change the name name to DEFAULT_ITEMS_PER_PAGE. The default value is 9 because that is the natural page count for the GIBCT (3 rows of 3 columns of schools in the search). Cheating I know...
